version: '3.7'

services:
  frontend: 
    build: ./client
    ports:
      - 8080:8080
    volumes: 
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - featurechecker
  backend: 
    build: ./server
    ports:
      - 5000:5000
    links:
      - database
    volumes: 
      - ./server:/usr/src/server
      - node_modules_b:/usr/src/server/node_modules
    networks:
      - featurechecker
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - 27010:27010
    networks:
      - featurechecker
    volumes:
      - data:/data/db
networks:
  featurechecker:
volumes:
  data:
  node_modules:
  node_modules_b:
