version: '3.7'

services:
  frontend: 
    build: client
    ports:
      - "8080:8080"
    volumes: 
      - ./client:/client
    networks:
      - featurechecker
  backend: 
    build: server
    ports:
      - "5000:5000"
    links:
      - database
    volumes: 
      - ./backend:/backend
    networks:
      - featurechecker
  database:
    image: mongo
    ports:
      - "27010:27010"
    networks:
      - featurechecker
    volumes:
      - dbdata:/data/db
networks:
  featurechecker:
volumes:
  dbdata:
