version: '3'
services:
  server:
    build:
      context: ./server
    command: node src/server.js
    container_name: TST_api
    environment:
      - PORT=4000
      - VIRTUAL_HOST=2000
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./server/src:/app/server/src
  client:
    build:
      context: ./client
    container_name: TST_client
    links:
      - server
    ports:
      - 81:80
      - 70:443
    restart: always