name: prod deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HAYUNA_HOST }}
          username: ${{ secrets.HAYUNA_USERNAME }}
          password: ${{ secrets.HAYUNA_PASSWORD }}
          port: ${{ secrets.HAYUNA_PORT }}
          timeout: 30m
          command_timeout: 60m  
          script: |
            cd /home/github
            git pull origin master
            docker-compose down -v
            API_KEY_GOOGLE=${{ secrets.API_KEY_GOOGLE }} CSE_ID_GOOGLE=${{ secrets.CSE_ID_GOOGLE }} docker-compose up --build -d
