name: test deploy
on: 
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HAYUNA_HOST }}
          username: ${{ secrets.HAYUNA_USERNAME }}
          password: ${{ secrets.HAYUNA_PASSWORD }}
          port: ${{ secrets.HAYUNA_PORT }}
          timeout: 30m
          command_timeout: 60m  
          script: |
            cd /home/test
            git pull origin test
            docker-compose down -v
            docker-compose up --build -d
